config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

  resources :movies

  resources :users, except: [:new]
  get "signup", to: "users#new"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  post "rate", to: "ratings#rate"
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  #Runs :set_movie method before anything else
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  #User should be logged in to perform all other actions
  before_action :require_user, except: [:show, :index]

  #User should be movie's user
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /movies
  def index
    #@movies = Movie.all
    @movies = Movie.paginate(page: params[:page], per_page: 4)
  end

  # GET /movies/{id}
  def show
    @ratings = @movie.ratings
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end


  # GET /movies/{id}/edit
  def edit
  end

  # POST /movies
  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user
    if @movie.save
      flash[:notice] = "Movie was created successfully"
      redirect_to @movie
    else
      render 'new'
    end
  end

  # PATCH/PUT /movies/{id}
  def update
    if @movie.update(movie_params)
      flash[:notice] = "Movie was updated successfully"
      redirect_to @movie
    else
      render 'new'
    end
  end

  # DELETE /movies/{id}
  def destroy
    @movie.destroy
    flash[:notice] = "Movie was deleted successfully"
    redirect_to movies_path
  end

  def search
    @movies = Movie.paginate(page: params[:page], per_page: 4)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :description)
    end

    # Only allow the movie's user to perform the action(s)
    def require_same_user
      if current_user != @movie.user && !current_user.admin?
        flash[:alert] = "You can only edit your own movie(s)"
        redirect_to @movie
      end
    end

end

app/views/movies/_form.html.erb
<div class="container"> 
  <div class="row justify-content-center">
    <div class="col-10"> 
      <%= render 'shared/validation_errors', obj: @movie %>   
      <%= form_with(model: @movie, local: true, class: "apptheme shadow p-3 mb-3 rounded") do |form| %>
        <div class="form-group row">
          <%= form.label :title, class: "col-2 col-form-label text-white" %> <br>
          <div class="col-10">
            <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Title of movie" %>
          </div>   
        </div>
        <div class="form-group row">
          <%= form.label :description, class: "col-2 col-form-label text-white" %> <br>
          <div class="col-10">
            <%= form.text_area :description, class: "form-control shadow rounded", placeholder: "Description of movie", rows: 10 %>
          </div>   
        </div>
        <div class="form-group row justify-content-center">
        <%= form.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  
  </div>
  <div class="row justify-content-center">
    <%= link_to "[ Return to movies ]", movies_path, class: "text-white mb-3" %>
  </div>
</div>

app/views/movies/_movie.html.erb
<%= javascript_pack_tag 'test' %>
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-body">
        <h5 class="card-title"><%= link_to movie.title, movie, class: "apptheme-txt" %></h5>
        <p class="card-text text-left">
          <%= simple_format(movie.description, length: 100) %>
        </p>
        <div id="ratings-div-<%= movie.id %>">
          <% if movie.ratings.any? %>
            <p>
              <span class="text-success"><%= pluralize(movie.likes, "Like") if movie.likes > 0 %></span>
              <span class="text-danger"><%= pluralize(movie.hates, "Hate") if movie.hates > 0 %></span>
            </p>
          <% end %>
          <% if logged_in? %>
            <% if current_user != movie.user %>
              <p>
                <!-- LIKE BUTTON -->
                <% if !current_user.hasRated(movie) || !current_user.likes(movie) %>
                  <%= link_to "Like", rate_path(movie: movie, value: 1), method: :post, remote: true , class: "btn rate-btn btn-outline-success"%>
                <% else %>
                  <%= link_to "Unlike", rate_path(movie: movie, value: 1), method: :post, remote: true , class: "btn rate-btn btn-success"%>
                <% end %>
                <!-- HATE BUTTON -->                 
                <% if !current_user.hasRated(movie) || !current_user.hates(movie) %> 
                  <%= link_to "Hate", rate_path(movie: movie, value: -1), method: :post, remote: true , class: "btn rate-btn btn-outline-danger" %>
                <% else %>
                  <%= link_to "Unhate", rate_path(movie: movie, value: -1), method: :post, remote: true , class: "btn rate-btn btn-danger" %>
                <% end %>
              </p>
            <% end %>
            <% if current_user == movie.user || current_user.admin? %>
              <%= link_to 'Edit', edit_movie_path(movie), class: "btn btn-info" %>
              <%= link_to 'Delete', movie, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger" %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="card-footer">
        <small class="text-muted">              
          Created by 
          <% if movie.user %>
                  by <%= link_to movie.user.username, user_path(movie.user) %>
                <% else %>
                  by Unknown
                <% end %>
          <%= time_ago_in_words(movie.created_at) %> ago 
          (last edited <%= time_ago_in_words(movie.updated_at) %> ago)
        </small>
      </div>
    </div>
  </div>
</div>

app/views/movies/_movie_form.html.erb
<div class="container"> 
  <div class="row justify-content-center">
    <div class="col-10"> 
      <%= render 'shared/validation_errors', obj: @movie %>   
      <%= form_with(model: @movie, local: true, class: "apptheme shadow p-3 mb-3 rounded") do |form| %>
        <div class="form-group row">
          <%= form.label :title, class: "col-2 col-form-label text-white" %> <br>
          <div class="col-10">
            <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Title of movie" %>
          </div>   
        </div>
        <div class="form-group row">
          <%= form.label :description, class: "col-2 col-form-label text-white" %> <br>
          <div class="col-10">
            <%= form.text_area :description, class: "form-control shadow rounded", placeholder: "Description of movie", rows: 10 %>
          </div>   
        </div>
        <div class="form-group row justify-content-center">
        <%= form.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  
  </div>
  <div class="row justify-content-center">
    <%= link_to "[ Return to movies ]", movies_path, class: "apptheme-txt mb-3" %>
  </div>
</div>

app/views/movies/_movies.html.erb
<div class="flickr_pagination mt-4 mb-4">
  <%= will_paginate @movies, :container => false %>
</div>

<div class="container">
    <%= render @movies%>
</div>

<div class="flickr_pagination mt-4 mb-4">
  <%= will_paginate @movies, :container => false %>
</div>

app/views/movies/_ratings.html.erb
<% if @movie.ratings.any? %>
  <p>
    <span class="text-success"><%= pluralize(@movie.likes, "Like") if @movie.likes > 0 %></span>
    <span class="text-danger"><%= pluralize(@movie.hates, "Hate") if @movie.hates > 0 %></span>
  </p>
<% end %>
<% if logged_in? %>
  <% if current_user != @movie.user %>
    <p>
      <!-- LIKE BUTTON -->
      <% if !current_user.hasRated(@movie) || !current_user.likes(@movie) %>
        <%= link_to "Like", rate_path(movie: @movie, value: 1), method: :post, remote: true , class: "btn rate-btn btn-outline-success"%>
      <% else %>
        <%= link_to "Unlike", rate_path(movie: @movie, value: 1), method: :post, remote: true , class: "btn rate-btn btn-success"%>
      <% end %>
      <!-- HATE BUTTON -->                 
      <% if !current_user.hasRated(@movie) || !current_user.hates(@movie) %> 
        <%= link_to "Hate", rate_path(movie: @movie, value: -1), method: :post, remote: true , class: "btn rate-btn btn-outline-danger" %>
      <% else %>
        <%= link_to "Unhate", rate_path(movie: @movie, value: -1), method: :post, remote: true , class: "btn rate-btn btn-danger" %>
      <% end %>
    </p>
  <% end %>
  <% if current_user == @movie.user || current_user.admin? %>
    <%= link_to 'Edit', edit_movie_path(@movie), class: "btn btn-info" %>
    <%= link_to 'Delete', @movie, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger" %>
  <% end %>
<% end %>

app/views/movies/_ratings.js.erb
document.querySelector("#ratings-div-<%= j @movie.id %>").innerHTML = '<%= j render 'movies/ratings.html' %>';

app/views/movies/edit.html.erb
<h1 class="text-center mt-4 apptheme-txt">Edit movie</h1>

<%= render 'form', movie: @movie %>

app/views/movies/index.html.erb
<h1 class="text-center mt-4 apptheme-txt">Movies</h1>

<% if logged_in? %>

  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <%= link_to "Create movie", new_movie_path, class: "btn btn-success" %>
      </div>
    </div>
  </div>
<% end %>

<%= render 'movies' %>  

app/views/movies/new.html.erb
<h1 class="text-center mt-4 apptheme-txt">Create new movie</h1>

<%= render 'form', movie: @movie %>

app/views/movies/show.html.erb
<div class="container">  
  <%= render @movie %>
  <div class="row justify-content-center">
    <%= link_to "[ Return to movies ]", movies_path, class: "text-white mb-3" %>
  </div>
</div>