config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

  resources :movies

  resources :users, except: [:new]
  get "signup", to: "users#new"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  post "rate", to: "ratings#rate"
end

app/views/layouts/_flash_messages.html.erb
<div class="container">
  <% flash.each do |key, msg| %>
    <div class="alert alert-<%= key == "alert" ? "danger" : "success" %> alert-dismissible fade show" role="alert">
      <%= msg %>    
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div> 
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-light text-dark">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Anastasia Kassari", "https://www.github.com/anastasiakassari", class: "apptheme-txt" %></small>    
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "The Movies Club", root_path, class: "navbar-brand apptheme-txt", id: "nav-logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Movies
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to('Create new movie', new_movie_path, class: "dropdown-item") if logged_in? %>
          <%= link_to 'View movies', movies_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <% if !logged_in? %>
        <li class="nav-item">
          <%= link_to "Log in", login_path, class: "btn btn-outline-info" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "btn btn-outline-success" %>
        </li>
      <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle apptheme-txt" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'View profile', user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Edit account', edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Delete account', current_user, method: :delete, data: { confirm: "Are you sure?"}, class: "dropdown-item text-danger" %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", logout_path, method: :delete, class: "btn btn-outline-info" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Movies Club</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">      
      <%= render 'layouts/flash_messages' %>    
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>